original_labels = {
    "Health_status": {"Unhealthy": 0, "Healthy": 1},
    "Sex": {"male": 1, "female": 2},
    "Age_group":{"1 - 3": 1, "3 - 6": 2, "6 - 8": 3, "8 - 10": 4, "10 - 12": 5, "> 12": 6},
    "Breed": {"Mixed": 1, "Pure": 2},
    "Neutered_status": {"Intact": 1, "Neutered": 2},
    "Sensory_problems":{"No":0, "Yes": 1},
    "Offleash_activity": {"Less than 30 mins": 1, "30 mins - 1 hour": 2, ">1 - 3 hours": 3, ">3 - 7 hours": 4, "More than 7 hours": 5},
    "Body_condition_score": {"Thin": 1, "Over-weight": 2, "Normal": 3}, 
    "Food": {"Dry food only": 1, "Tinned and dry food": 2, "Cooked food": 3, "Mixed": 4, "Raw food": 5},
    "Vitamins": {"Almost never": 1, "Rarely": 2, "Often": 3, "Regularly (daily)": 4}, 
    "Trauma": {"No": 0, "Yes": 1},
    "Health_problems": {"None": 0, "tooth problems": 1, "joint problems + tooth problems": 2, "joint problems": 3, "other disorders": 4}, 
    "Medication": {"No": 0, "Yes": 1},
    "Owner_gender": {"Male": 1, "Female": 2}, 
    "Owner_age":{"<29 years":1, "30 - 39 years":2, "40 - 49 years":3, ">50 years":4},
    "Owner_experience": {"Dogs are my hobby/profession": 1, "I have had a dog before": 2, "I have never had a dog before": 3}, 
    "Other_dogs_in_house": {"None": 0, "One": 1, "Two or more": 2}, 
    "People_in_household": {"One person": 1, "Two people": 2, "Three people": 3, "Four or more people": 4}, 
    "Child": {"No": 0, "Yes": 1},
    "Age_of_dog_when_arrived": {"Less than 7 weeks": 1, "7 - 12 weeks": 2, "3 - 12 months": 3, "More than a year": 4}, 
    "get_dog": {"Found it/shelter": 1, "Born at my place/bought it": 2, "Got as a present": 3}, 
    "Where_dog_is_kept": {"House with garden/non fenced area": 1, "Fenced garden": 2, "Urban/suburban apartment": 3}, 
    "Dog_obedience_tasks": {"Maximum a task": 1, "2 kinds of tasks": 2, "3 kinds of tasks": 3, "4 or more kinds of tasks": 4}, 
    "Play": {"Less than 30 mins": 1, "30 mins - 1 hour": 2, ">1 - 3 hours": 3, "more than 3 hours": 4}, 
    "Commands": {"<10 commands": 1, "11 - 30 commands": 2, ">30 commands": 3}, 
    "Dog_training_activities": {"One activity": 1, "2 - 3 activities": 2, "4 or more activities": 3}, 
    "Time_dog_spend_alone": {"None": 1, "1 - 2 hours": 2, "3 - 8 hours": 3, "More than 8 hours": 4}, 
    "Dog_beh_changed_3month": {"No": 0, "Yes": 1}, 
    "Life_event_mating_pregnancy": {"No": 0, "Yes": 1},
    "Life_event_change_in_family_structure": {"No": 0, "Yes": 1},
    "Life_event_No_dogs_household_changed": {"No": 0, "Yes": 1}, 
    "Life_event_moved_house": {"No": 0, "Yes": 1},
    "Life_event_changed_owners": {"No": 0, "Yes": 1},
    "Life_event_spent_more_time_alone": {"No": 0, "Yes": 1},
    "Life_event_lost": {"No": 0, "Yes": 1},
    "Life_event_injury_surgery": {"No": 0, "Yes": 1},
    "Life_event_spent_time_at_shelter": {"No": 0, "Yes": 1},
    "Life_events": {"None": 0, "One": 1, "Two": 2, "Three or more": 3}
}

labels = {
    "Health_status": {"Healthy": 0, "Unhealthy": 1},
    "Sex": {"male": 0, "female": 1},
    "Age_group":{"1 - 3": 1, "3 - 6": 2, "6 - 8": 3, "8 - 10": 4, "10 - 12": 5, "> 12": 6},
    "Breed": {"Mixed": 0, "Pure": 1},
    "Neutered_status": {"Intact": 0, "Neutered": 1},
    "Sensory_problems":{"No":0, "Yes": 1},
    "Offleash_activity": {"Less than 30 mins": 1, "30 mins - 1 hour": 2, ">1 - 3 hours": 3, ">3 - 7 hours": 4, "More than 7 hours": 5},
    "Body_condition_score": {"Thin": 1, "Over-weight": 2, "Normal": 3}, 
    "Food": {"Dry food only": 1, "Tinned and dry food": 2, "Cooked food": 3, "Mixed": 4, "Raw food": 5},
    "Vitamins": {"Almost never": 1, "Rarely": 2, "Often": 3, "Regularly (daily)": 4}, 
    "Trauma": {"No": 0, "Yes": 1},
    "Health_problems": {"None": 0, "tooth problems": 1, "joint problems + tooth problems": 2, "joint problems": 3, "other disorders": 4}, 
    "Medication": {"No": 0, "Yes": 1},
    "Owner_gender": {"Male": 0, "Female": 1}, 
    "Owner_age":{"<29 years":1, "30 - 39 years":2, "40 - 49 years":3, ">50 years":4},
    "Owner_experience": {"Dogs are my hobby/profession": 1, "I have had a dog before": 2, "I have never had a dog before": 3}, 
    "Other_dogs_in_house": {"None": 0, "One": 1, "Two or more": 2}, 
    "People_in_household": {"One person": 1, "Two people": 2, "Three people": 3, "Four or more people": 4}, 
    "Child": {"No": 0, "Yes": 1},
    "Age_of_dog_when_arrived": {"Less than 7 weeks": 1, "7 - 12 weeks": 2, "3 - 12 months": 3, "More than a year": 4}, 
    "get_dog": {"Found it/shelter": 1, "Born at my place/bought it": 2, "Got as a present": 3}, 
    "Where_dog_is_kept": {"House with garden/non fenced area": 1, "Fenced garden": 2, "Urban/suburban apartment": 3}, 
    "Dog_obedience_tasks": {"Maximum a task": 1, "2 kinds of tasks": 2, "3 kinds of tasks": 3, "4 or more kinds of tasks": 4}, 
    "Play": {"Less than 30 mins": 1, "30 mins - 1 hour": 2, ">1 - 3 hours": 3, "more than 3 hours": 4}, 
    "Commands": {"<10 commands": 1, "11 - 30 commands": 2, ">30 commands": 3}, 
    "Dog_training_activities": {"One activity": 1, "2 - 3 activities": 2, "4 or more activities": 3}, 
    "Time_dog_spend_alone": {"None": 1, "1 - 2 hours": 2, "3 - 8 hours": 3, "More than 8 hours": 4}, 
    "Dog_beh_changed_3month": {"No": 0, "Yes": 1}, 
    "Life_event_mating_pregnancy": {"No": 0, "Yes": 1},
    "Life_event_change_in_family_structure": {"No": 0, "Yes": 1},
    "Life_event_No_dogs_household_changed": {"No": 0, "Yes": 1}, 
    "Life_event_moved_house": {"No": 0, "Yes": 1},
    "Life_event_changed_owners": {"No": 0, "Yes": 1},
    "Life_event_spent_more_time_alone": {"No": 0, "Yes": 1},
    "Life_event_lost": {"No": 0, "Yes": 1},
    "Life_event_injury_surgery": {"No": 0, "Yes": 1},
    "Life_event_spent_time_at_shelter": {"No": 0, "Yes": 1},
    "Life_events": {"None": 0, "One": 1, "Two": 2, "Three or more": 3}
}
